"""add_dispatch_fields_to_event

Revision ID: 873602d4c842
Revises: d455377f82ef
Create Date: 2026-03-31 12:12:21.909268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873602d4c842'
down_revision: Union[str, None] = 'd455377f82ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('handled_by', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('handled_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'events', 'admins', ['handled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'handled_at')
    op.drop_column('events', 'handled_by')
    # ### end Alembic commands ###
