"""add_employee_id_to_admin

Revision ID: d455377f82ef
Revises: b5521f8a3c10
Create Date: 2026-03-31 12:08:08.002264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd455377f82ef'
down_revision: Union[str, None] = 'b5521f8a3c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('employee_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_admins_employee_id'), 'admins', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_employee_id'), table_name='admins')
    op.drop_column('admins', 'employee_id')
    # ### end Alembic commands ###
